config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboards#show'

  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resource :session, controller: 'clearance/sessions', only: [:create]

  resources :users, controller: 'clearance/users', only: [:create] do
    resource :password,
      controller: 'clearance/passwords',
      only: [:create, :edit, :update]
  end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign_up' => 'clearance/users#new', as: 'sign_up'
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div id="flash">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header">
    <% if signed_in? -%>
      <%= button_to t('.sign_out'), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t('.sign_in'), sign_in_path %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>

app/views/refills/_flashes.html.erb
<div class="flash-success">
  <span>This is a success message <a href="#">with a link</a></span>
</div>

<div class="flash-error">
  <span>This is an error message <a href="#">with a link</a></span>
</div>

<div class="flash-notice">
  <span>This is an notice message <a href="#">with a link</a></span>
</div>

<div class="flash-alert">
  <span>This is an alert message <a href="#">with a link</a></span>
</div>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t('.title') %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t('.sign_in'), sign_in_path %>
    </div>
  <% end %>
</div>